global:
  prefix: imposter
  version: 0.1.0

namespace:
  create: true
  name: mountebank

deployment:
  replicas: 1
  annotate:
    imposters.helm.created-by: "helm-imposter-installer"
  image:
    name: "bbyars/mountebank"
    version: "2.8.1"
  resources:
    request:
      memory: 512Mi
      cpu: 256m
    limits:
      memory: 1536Mi
      cpu: 1000m

service:
  type: ClusterIP
  port: 2525
  imposters:
    portRange:
      initPort: 4040
      endPort: 4045
  healthCheck:
    readiness:
      path: /config
    liveness:
      path: /config

security:
  context:
    userId: 1000
    isRoot: false
    isPrivileged: false