{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "global.namespace" . }}
  labels:
    istio-injection: enable
    name: {{ template "global.namespace" . }}
{{- end}}